export const beats = [
    {
        cover: './images/covers/shooting-star-cover.png',
        title: 'shooting star',
        bpm: '158',
        key: 'Amin',
        time: '02:13',
        genres: ['hip-hop', 'hyperpop', 'guitar'],
        audio: './audio/shootingstar.mp3',
        link: 'https://bsta.rs/sKCzJZ',
    },
    {
        cover: './images/covers/lovbug-cover.png',
        title: 'lovbug',
        bpm: '160',
        key: 'Emin',
        time: '01:48',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/lovbug.mp3',
        link: 'https://bsta.rs/IiKur',
    },
    {
        cover: './images/covers/3am-cover.png',
        title: '3am',
        bpm: '170',
        key: 'F#min',
        time: '01:41',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/3am.mp3',
        link: 'https://bsta.rs/OwmrB',
    },
    {
        cover: './images/covers/hammer-cover.png',
        title: 'hammer',
        bpm: '150',
        key: 'Amin',
        time: '01:55',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/hammer.mp3',
        link: 'https://bsta.rs/vh7zj8',
    },
    {
        cover: './images/covers/overdose-cover.png',
        title: 'overdose',
        bpm: '140',
        key: 'Bmin',
        time: '02:03',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/overdose.mp3',
        link: 'https://bsta.rs/rxeGop',
    },
    {
        cover: './images/covers/memory-cover.png',
        title: 'memory',
        bpm: '140',
        key: 'Am',
        time: '02:03',
        genres: ['hip-hop', 'hyperpop', 'ripsquad'],
        audio: './audio/memory.mp3',
        link: 'https://bsta.rs/zbEdev',
    },
    {
        cover: './images/covers/classic-cover.png',
        title: 'classic',
        bpm: '140',
        key: 'Emin',
        time: '02:03',
        genres: ['hip-hop', 'hyperpop', 'ripsquad'],
        audio: './audio/classic.mp3',
        link: 'https://bsta.rs/PpqIvL',
    },
    {
        cover: './images/covers/scratch-cover.png',
        title: 'scratch',
        bpm: '160',
        key: 'F#min',
        time: '01:48',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/scratch.mp3',
        link: 'https://bsta.rs/ZrBglp',
    },
    {
        cover: './images/covers/t1meless-cover.png',
        title: 't1meless',
        bpm: '170',
        key: 'G#min',
        time: '02:04',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/t1meless.mp3',
        link: 'https://bsta.rs/Z0Xiw',
    },
    {
        cover: './images/covers/jerkdigicore-cover.png',
        title: 'jerkdigicore',
        bpm: '180',
        key: 'D#min',
        time: '01:46',
        genres: ['hip-hop', 'hyperpop', 'jerk'],
        audio: './audio/jerkdigicore.mp3',
        link: 'https://bsta.rs/G8Yg5D',
    },
    {
        cover: './images/covers/topof-cover.png',
        title: 'topof',
        bpm: '140',
        key: 'Fmin',
        time: '01:49',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/topof.mp3',
        link: 'https://bsta.rs/SdL4Ci',
    },
    {
        cover: './images/covers/magic-cover.png',
        title: 'magic',
        bpm: '171',
        key: 'Cmin',
        time: '01:41',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/magic.mp3',
        link: 'https://bsta.rs/Hl2Mth',
    },
    {
        cover: './images/covers/hate-cover.png',
        title: 'hate',
        bpm: '180',
        key: 'Amin',
        time: '01:46',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/hate.mp3',
        link: 'https://bsta.rs/r7A3Kh',
    },
    {
        cover: './images/covers/gameover-cover.png',
        title: 'gameover',
        bpm: '140',
        key: 'G#min',
        time: '02:03',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/gameover.mp3',
        link: 'https://bsta.rs/ZnMyax',
    },
    {
        cover: './images/covers/whale-cover.png',
        title: 'whale',
        bpm: '140',
        key: 'Dmin',
        time: '02:25',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/whale.mp3',
        link: 'https://bsta.rs/MsQN5x',
    },
    {
        cover: './images/covers/snowfall-cover.png',
        title: 'snowfall',
        bpm: '140',
        key: 'Gmin',
        time: '02:03',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/snowfall.mp3',
        link: 'https://bsta.rs/7H2uO',
    },
    {
        cover: './images/covers/shortrise-cover.png',
        title: 'shortrise',
        bpm: '160',
        key: 'Gm',
        time: '02:00',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/shortrise.mp3',
        link: 'https://bsta.rs/2HW1d',
    },
    {
        cover: './images/covers/piro-cover.png',
        title: 'piro',
        bpm: '150',
        key: 'Am',
        time: '02:20',
        genres: ['hip-hop', 'hyperpop'],
        audio: './audio/piro.mp3',
        link: 'https://bsta.rs/31buy',
    },
    {
        cover: './images/covers/bling-cover.png',
        title: 'bling',
        bpm: '160',
        key: 'Emin',
        time: '02:00',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/bling.mp3',
        link: 'https://bsta.rs/Rpn7mg',
    },
    {
        cover: './images/covers/fucc_tha_club_up-cover.png',
        title: 'fucc tha club up',
        bpm: '140',
        key: 'Amin',
        time: '02:33',
        genres: ['hip-hop', 'hyperpop', 'dance'],
        audio: './audio/fucc-tha-club-up.mp3',
        link: 'https://bsta.rs/GOerAm',
    },
    {
        cover: './images/covers/alx-cover.png',
        title: 'alx',
        bpm: '180',
        key: 'Dmin',
        time: '01:52',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/alx.mp3',
        link: 'https://bsta.rs/Wsmb3i',
    },
    {
        cover: './images/covers/tpp-cover.png',
        title: 'tpp',
        bpm: '160',
        key: 'Cmin',
        time: '02:00',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/tpp.mp3',
        link: 'https://bsta.rs/ojtxuQ',
    },
    {
        cover: './images/covers/fireflies-cover.png',
        title: 'fireflies',
        bpm: '140',
        key: 'F#min',
        time: '02:03',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/fireflies.mp3',
        link: 'https://bsta.rs/wWbq4',
    },
    {
        cover: './images/covers/elctrix-cover.png',
        title: 'elctrix',
        bpm: '165',
        key: 'F#min',
        time: '02:08',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/elctrix.mp3',
        link: 'https://bsta.rs/y9I7YG',
    },
    {
        cover: './images/covers/alien-cover.png',
        title: 'alien',
        bpm: '168',
        key: 'Dmin',
        time: '02:05',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/alien.mp3',
        link: 'https://bsta.rs/Xi7JSK',
    },
    {
        cover: './images/covers/likeisaid-cover.png',
        title: 'likeisaid',
        bpm: '175',
        key: 'Fmin',
        time: '02:00',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/likeisaid.mp3',
        link: 'https://bsta.rs/ajzE8X',
    },
    {
        cover: './images/covers/egirl-cover.png',
        title: 'egirl',
        bpm: '176',
        key: 'F#min',
        time: '02:00',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/egirl.mp3',
        link: 'https://bsta.rs/BAGich',
    },
    {
        cover: './images/covers/whatiwant-cover.png',
        title: 'whatiwant',
        bpm: '160',
        key: 'Em',
        time: '02:12',
        genres: ['hip-hop', 'hyperpop', 'elxnce'],
        audio: './audio/whatiwant.mp3',
        link: 'https://bsta.rs/EwuDKI',
    },
    {
        cover: './images/covers/amb-cover.png',
        title: 'amb',
        bpm: '127',
        key: 'G#min',
        time: '02:44',
        genres: ['ambient', 'hyperpop', 'jequya'],
        audio: './audio/amb.mp3',
        link: 'https://bsta.rs/lO50Tn',
    },
    {
        cover: './images/covers/lowlow-cover.png',
        title: 'lowlow',
        bpm: '140',
        key: 'Am',
        time: '02:44',
        genres: ['digicore', 'hyperpop', 'scenecore'],
        audio: './audio/lowlow.mp3',
        link: 'https://bsta.rs/xhytq7',
    },
    {
        cover: './images/covers/gunshot-cover.png',
        title: 'gunshot',
        bpm: '160',
        key: 'G#min',
        time: '02:12',
        genres: ['digicore', 'hyperpop', 'elxnce'],
        audio: './audio/gunshot.mp3',
        link: 'https://bsta.rs/rY2oZg',
    },
    {
        cover: './images/covers/glitch-cover.png',
        title: 'glitch',
        bpm: '175',
        key: 'Bm',
        time: '02:33',
        genres: ['digicore', 'hyperpop', 'happy'],
        audio: './audio/glitch.mp3',
        link: 'https://bsta.rs/mTVZ1',
    },
    {
        cover: './images/covers/torture-cover.png',
        title: 'torture',
        bpm: '160',
        key: 'D#min',
        time: '02:00',
        genres: ['digicore', 'hyperpop', 'elxnce'],
        audio: './audio/torture.mp3',
        link: 'https://bsta.rs/Op5Q6',
    },
    {
        cover: './images/covers/thunder-cover.png',
        title: 'thunder',
        bpm: '164',
        key: 'G#min',
        time: '02:32',
        genres: ['digicore', 'hyperpop', 'elxnce'],
        audio: './audio/thunder.mp3',
        link: 'https://bsta.rs/kz8Oi',
    },
    {
        cover: './images/covers/drippin-cover.png',
        title: 'drippin',
        bpm: '140',
        key: 'A#min',
        time: '02:18',
        genres: ['guitar', 'hyperpop', 'drippinsopretty'],
        audio: './audio/drippin.mp3',
        link: 'https://bsta.rs/pwFeMW',
    },
    {
        cover: './images/covers/moon-cover.png',
        title: 'moon',
        bpm: '155',
        key: 'F#min',
        time: '01:53',
        genres: ['osamason', 'nettspend', 'ok'],
        audio: './audio/moon.mp3',
        link: 'https://bsta.rs/InKwZx',
    },
    {
        cover: './images/covers/shift-cover.png',
        title: 'shift',
        bpm: '156',
        key: 'G#min',
        time: '02:15',
        genres: ['hyperpop', 'digicore', 'ripsquad'],
        audio: './audio/shift.mp3',
        link: 'https://bsta.rs/nvxfyr',
    },
    {
        cover: './images/covers/nylon-cover.png',
        title: 'nylon',
        bpm: '156',
        key: 'F#min',
        time: '02:40',
        genres: ['yandere', 'pluggnb', 'hyperpop'],
        audio: './audio/nylon.mp3',
        link: 'https://bsta.rs/831WGX',
    },
    {
        cover: './images/covers/fatal-cover.png',
        title: 'fatal',
        bpm: '178',
        key: 'F#m',
        time: '01:58',
        genres: ['digicore', 'elxnce', 'hyperpop'],
        audio: './audio/fatal.mp3',
        link: 'https://bsta.rs/6dm64k',
    },
    {
        cover: './images/covers/cym-cover.png',
        title: 'cym',
        bpm: '170',
        key: 'Bmin',
        time: '02:38',
        genres: ['digicore', 'elxnce', 'hyperpop'],
        audio: './audio/cym.mp3',
        link: 'https://bsta.rs/dVfDbR',
    },
    {
        cover: './images/covers/slice-cover.png',
        title: 'slice',
        bpm: '160',
        key: 'D#min',
        time: '02:36',
        genres: ['digicore', 'vinso', 'hyperpop'],
        audio: './audio/slice.mp3',
        link: 'https://bsta.rs/GJSbwp',
    },
    {
        cover: './images/covers/somerock-cover.png',
        title: 'somerock',
        bpm: '160',
        key: 'A#min',
        time: '02:24',
        genres: ['digicore', 'rock', 'hyperpop'],
        audio: './audio/somerock.mp3',
        link: 'https://bsta.rs/fZzuNS',
    },
    {
        cover: './images/covers/killme-cover.png',
        title: 'killme',
        bpm: '160',
        key: 'F#min',
        time: '02:12',
        genres: ['digicore', 'ripsquad', 'hyperpop'],
        audio: './audio/killme.mp3',
        link: 'https://bsta.rs/OFwvj0',
    },
    {
        cover: './images/covers/arldead-cover.png',
        title: 'arldead',
        bpm: '169',
        key: 'G#min',
        time: '02:05',
        genres: ['digicore', 'ripsquad', 'hyperpop'],
        audio: './audio/arldead.mp3',
        link: 'https://bsta.rs/swLRT',
    },
    {
        cover: './images/covers/gratefull-cover.png',
        title: 'gratefull',
        bpm: '155',
        key: 'Am',
        time: '02:28',
        genres: ['digicore', 'dolly', 'hyperpop'],
        audio: './audio/grateful.mp3',
        link: 'https://bsta.rs/6GXYwL',
    },
]
